services:
  temporal:
    build:
      context: ./containers/temporal-server
      dockerfile: Containerfile
    environment:
      - DB=postgres12
      - DB_PORT=${DB_PORT:-5432}
      - POSTGRES_SEEDS=${POSTGRES_SEEDS:-localhost}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PWD=${POSTGRES_PWD:-postgres}
      - DBNAME=${DBNAME:-postgres}
      - VISIBILITY_DBNAME=${VISIBILITY_DBNAME:-postgres_visibility}
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - SKIP_DB_CREATE=false
      - SKIP_SCHEMA_SETUP=false
    ports:
      - "7233:7233"
    volumes:
      - ./config/dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-ui:
    build:
      context: ./containers/temporal-ui
      dockerfile: Containerfile
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    ports:
      - "8080:8080"
